[package]
name = "fluvio-future"
version = "0.1.11"
edition = "2018"
authors = ["fluvio.io"]
description = "I/O futures for Fluvio project"
repository = "https://github.com/infinyon/future-aio"
license = "Apache-2.0"

[features]
task = ["async-std/default", "timer"]
subscriber = ["tracing-subscriber"]
fixture = ["subscriber", "task", "fluvio-test-derive"]
task_unstable = ["task", "async-std/unstable"]
io = ["async-std/default"]
net = ["futures-lite", "async-net", "async-trait"]
tls = ["rust_tls"]
rust_tls = ["net", "rustls", "webpki", "fluvio-async-tls", "pin-project"]
native2_tls = ["net","pin-project","async-native-tls","native-tls","openssl"]
timer = ["async-io","pin-project","futures-lite"]
fs = ["async-fs", "futures-lite", "pin-utils"]
zero_copy = ["nix", "task_unstable"]
mmap = ["fs", "memmap", "task_unstable"]

[dependencies]
log = "0.4.0"
futures-lite = { version = "1.11.2", optional = true }
futures-timer = { version = "3.0.0", optional = true }
async-std = { version = "1.6.0", default-features = false, optional = true }
async-io = { version = "1.1.2", optional = true }
async-fs = { version = "1.3.0", optional = true }
async-net = { version = "1.3.0", optional = true }
pin-utils = { version = "0.1.0", optional = true }
pin-project = { version = "1.0.1", optional = true }
tracing = { version = "0.1.0" }
tracing-subscriber = { version = "0.2.0", optional = true }
nix = { version = "0.17.0", optional = true }
bytes = { version = "0.5.0", optional = true }
memmap = { version = "0.7.0", optional = true }
async-trait = { version = "0.1.40", optional = true }
rustls = { version = "0.18.0", features = ["dangerous_configuration"], optional = true }
async-native-tls = { version = "0.3.3", optional = true }
native-tls = { version = "0.2.4", optional = true }
openssl = { version = "0.10.30", optional = true, features = ["vendored"] }
webpki = { version = "0.21", optional = true }
fluvio-async-tls = { version = "0.1.0", optional = true }
thiserror = "1.0.20"
fluvio-test-derive = { path = "async-test-derive", version = "0.1.0", optional = true }

[dev-dependencies]
bytes = "0.5.6"
lazy_static = "1.2.0"
num_cpus = "1.10.1"
futures-util = { version = "0.3.5", features = ["sink"] }
async-lock = "2.0.0"
tokio-util = { version = "0.3.1", features = ["codec", "compat"] }
tokio = { version = "0.2.21", features = ["macros"] }
flv-util = { version = "0.5.0", features = ["fixture"] }
fluvio-test-derive = { path = "async-test-derive", version = "0.1.0" }
fluvio-future = { path = ".", features = ["net", "fixture", "timer", "fs"] }
