name: CI

on:
  push:
    branches: [ customRunner ]

jobs:

  smoke_test:
    name: Smoke test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        runs_on: [linux-ubuntu-bionic, macOS-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@v2
    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: Build
      run:  make build-all
    - name: Run unit tests
      run:  make test-all

